version: '2.4'
include:
  - docker-compose-eclipse-mosquitto.yml
services:
  prod-chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TOPIC=prod-order
      - MQTT_IP=ie-databus
      - MQTT_USER=edge
      - MQTT_PASSWORD=edge
      - DOCKER=1
    ports:
      - '8501:8501'
    mem_limit: 200mb # TODO: I don't think it is enough memory for the chatbot
    volumes:
      - './publish/:/publish/'
      - './cfg-data/:/cfg-data/'
      - './output/:/app/output/'
    networks:
      - proxy-redirect
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  nodered:
    image: nodered/node-red
    ports: 
      - 1880:1880
    networks:
      - proxy-redirect
networks:
    proxy-redirect: