name: CI Pipeline

on:
  push:
    branches:
      - package
      - $default-branch
  pull_request:
    branches:
      - package
      - $default-branch
  # workflow_dispatch:  # Manually triggered event
  #   inputs:
  #     odoo_args:
  #       description: 'Odoo Run Args'
  #       required: false
  #       default: ''

jobs:
  static-analysis:
    name: Python Linting Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify Python version (e.g., '3.8', '3.9', '3.x')

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint
        run: |
          pylint ./***/**/*.py